services:
  - type: web
    name: scoring-system-scout
    env: node
    plan: free
    region: oregon
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: your-jwt-secret-here
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE
        value: https://scoring-system-scout.onrender.com
