services:
  - type: web
    name: scoring-system-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: your-mongodb-uri-here
      - key: JWT_SECRET
        value: your-jwt-secret-here

  - type: static
    name: scoring-system-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://scoring-system-backend.onrender.com
